export const SECRET_REFS = {
  DATABASE_URL: 'op://Support/skill-cli/DATABASE_URL',
  FRONT_API_TOKEN: 'op://Support/skill-cli/FRONT_API_TOKEN',
  FRONT_WEBHOOK_SECRET: 'op://Support/skill-cli/FRONT_WEBHOOK_SECRET',
  SUPPORT_WEBHOOK_SECRET: 'op://Support/skill-cli/SUPPORT_WEBHOOK_SECRET',
  INNGEST_SIGNING_KEY: 'op://Support/skill-cli/INNGEST_SIGNING_KEY',
  INNGEST_EVENT_KEY: 'op://Support/skill-cli/INNGEST_EVENT_KEY',
  SLACK_BOT_TOKEN: 'op://Support/skill-cli/SLACK_BOT_TOKEN',
  SLACK_SIGNING_SECRET: 'op://Support/skill-cli/SLACK_SIGNING_SECRET',
  SLACK_APPROVAL_CHANNEL: 'op://Support/skill-cli/SLACK_APPROVAL_CHANNEL',
  UPSTASH_REDIS_REST_URL: 'op://Support/skill-cli/UPSTASH_REDIS_REST_URL',
  UPSTASH_REDIS_REST_TOKEN: 'op://Support/skill-cli/UPSTASH_REDIS_REST_TOKEN',
  UPSTASH_VECTOR_REST_URL: 'op://Support/skill-cli/UPSTASH_VECTOR_REST_URL',
  UPSTASH_VECTOR_REST_TOKEN: 'op://Support/skill-cli/UPSTASH_VECTOR_REST_TOKEN',
  STRIPE_SECRET_KEY: 'op://Support/skill-cli/STRIPE_SECRET_KEY',
  STRIPE_CONNECT_CLIENT_ID: 'op://Support/skill-cli/STRIPE_CONNECT_CLIENT_ID',
  STRIPE_WEBHOOK_SECRET: 'op://Support/skill-cli/STRIPE_WEBHOOK_SECRET',
  AXIOM_TOKEN: 'op://Support/skill-cli/AXIOM_TOKEN',
  LANGFUSE_PUBLIC_KEY: 'op://Support/skill-cli/LANGFUSE_PUBLIC_KEY',
  LANGFUSE_SECRET_KEY: 'op://Support/skill-cli/LANGFUSE_SECRET_KEY',
  BETTERAUTH_SECRET: 'op://Support/skill-cli/BETTERAUTH_SECRET',
  MYSQL_HOST: 'op://Support/skill-cli/MYSQL_HOST',
  MYSQL_PORT: 'op://Support/skill-cli/MYSQL_PORT',
  MYSQL_USER: 'op://Support/skill-cli/MYSQL_USER',
  MYSQL_PASSWORD: 'op://Support/skill-cli/MYSQL_PASSWORD',
  MYSQL_DATABASE: 'op://Support/skill-cli/MYSQL_DATABASE',
  QDRANT_URL: 'op://Support/skill-cli/QDRANT_URL',
  QDRANT_COLLECTION: 'op://Support/skill-cli/QDRANT_COLLECTION',
  OLLAMA_BASE_URL: 'op://Support/skill-cli/OLLAMA_BASE_URL',
  EMBEDDING_MODEL: 'op://Support/skill-cli/EMBEDDING_MODEL',
  AGE_SECRET_KEY: 'op://Support/skill-cli-age-key/private_key',
} as const

export type SecretRefKey = keyof typeof SECRET_REFS
export type SecretRef = (typeof SECRET_REFS)[SecretRefKey]
