import { writeFileSync } from 'fs'
import { generateKeypair } from '../../lib/crypto'

interface KeygenOptions {
  json?: boolean
  output?: string
}

/**
 * Generate age keypair for encryption
 */
export async function keygen(options: KeygenOptions = {}) {
  const { publicKey, privateKey } = await generateKeypair()

  if (options.json) {
    // JSON output mode
    console.log(JSON.stringify({ publicKey, privateKey }, null, 2))
  } else if (options.output) {
    // Write to file
    const content = `# Age keypair generated by skill CLI
# Public key (share this):
${publicKey}

# Private key (KEEP SECRET):
${privateKey}
`
    writeFileSync(options.output, content, 'utf-8')
    console.log(`Keypair written to ${options.output}`)
    console.error(
      `\n⚠️  WARNING: Private key written to disk. Keep ${options.output} secure!`
    )
  } else {
    // Normal mode: public to stdout, private to stderr with warning
    console.log(publicKey)
    console.error('\n⚠️  Private key (KEEP SECRET):')
    console.error(privateKey)
    console.error(
      '\n⚠️  Store this private key securely. Anyone with it can decrypt your data.'
    )
  }
}
