#!/usr/bin/env bun
/**
 * Add or update a key in .env.local
 * Usage: bun scripts/setup/add-key.ts KEY=value
 */

import { existsSync, readFileSync, writeFileSync } from 'fs'
import { resolve } from 'path'

const ENV_FILE = resolve(process.cwd(), '.env.local')

function parseEnvFile(path: string): Map<string, string> {
  const env = new Map<string, string>()

  if (!existsSync(path)) return env

  const content = readFileSync(path, 'utf-8')

  for (const line of content.split('\n')) {
    const trimmed = line.trim()
    if (!trimmed || trimmed.startsWith('#')) continue

    const [key, ...valueParts] = trimmed.split('=')
    const value = valueParts.join('=').trim()
    if (key) {
      env.set(key.trim(), value)
    }
  }

  return env
}

function writeEnvFile(path: string, env: Map<string, string>) {
  const lines: string[] = [
    '# Support Platform Configuration',
    '# Generated by setup scripts',
    '',
  ]

  // Group by service
  const groups: Record<string, string[]> = {
    'Front': ['FRONT_API_TOKEN', 'FRONT_WEBHOOK_SECRET', 'FRONT_INBOX_'],
    'Slack': ['SLACK_'],
    'Stripe': ['STRIPE_'],
    'Upstash': ['UPSTASH_'],
    'Cloudflare': ['CLOUDFLARE_'],
    'Axiom': ['AXIOM_'],
    'Langfuse': ['LANGFUSE_'],
    'PlanetScale': ['DATABASE_URL'],
    'BetterAuth': ['BETTERAUTH_'],
    'Other': [],
  }

  const used = new Set<string>()

  for (const [groupName, prefixes] of Object.entries(groups)) {
    const groupKeys = [...env.keys()].filter(key => {
      if (used.has(key)) return false
      return prefixes.some(p => key.startsWith(p))
    })

    if (groupKeys.length > 0) {
      lines.push(`# ${groupName}`)
      for (const key of groupKeys.sort()) {
        lines.push(`${key}=${env.get(key)}`)
        used.add(key)
      }
      lines.push('')
    }
  }

  // Add any remaining keys
  const remaining = [...env.keys()].filter(k => !used.has(k))
  if (remaining.length > 0) {
    lines.push('# Other')
    for (const key of remaining.sort()) {
      lines.push(`${key}=${env.get(key)}`)
    }
    lines.push('')
  }

  writeFileSync(path, lines.join('\n'))
}

// Main
const args = process.argv.slice(2)

if (args.length === 0) {
  console.log('Usage: bun scripts/setup/add-key.ts KEY=value')
  process.exit(1)
}

const env = parseEnvFile(ENV_FILE)

for (const arg of args) {
  const [key, ...valueParts] = arg.split('=')
  const value = valueParts.join('=')

  if (!key || !value) {
    console.error(`Invalid format: ${arg}`)
    continue
  }

  const existed = env.has(key)
  env.set(key, value)
  console.log(`${existed ? '📝 Updated' : '✅ Added'} ${key}`)
}

writeEnvFile(ENV_FILE, env)
console.log(`\n💾 Saved to ${ENV_FILE}`)
